# Change these first
owner: DimensionDev # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
- name: mask.io
  url: https://mask.io
- name: Maskbook UnlockProtocol plugin server
  url: https://unlock.r2d2.to
# RPC server used by Mask products
- name: RPC server - Infura Mainnet
  url: $INFURA_MAINNET_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Quiknode Mainnet
  url: $QUIKNODE_MAINNET_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Infura Ropsten
  url: $INFURA_ROPSTEN_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Infura Rinkeby
  url: $INFURA_RINKEBY_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Infura Kovan
  url: $INFURA_KOVAN_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Infura Gorli
  url: $INFURA_GORLI_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Binance BSC
  url: $BINANCE_BSC_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Binance BSCT
  url: $BINANCE_BSCT_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
- name: RPC server - Infura Matic Mainnet
  url: $INFURA_MATIC_MAINNET_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Infura Matic Mumbai
  url: $INFURA_MATIC_MUMBAI_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Arbitrum
  url: $ARBITRUM_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "0x"
  assignees:
    - frontendgatekeeper
- name: RPC server - Arbitrum Rinkeby
  url: $ARBITRUM_RINKEBY_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "0x"
  assignees:
    - frontendgatekeeper
- name: RPC server - xDai
  url: $XDAI_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Avalanche
  url: $AVALANCHE_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Avalanche Fuji
  url: $AVALANCHE_FUJI_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Celo
  url: $CELO_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Fantom
  url: $FANTOM_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Aurora
  url: $AURORA_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Aurora Testnet
  url: $AURORA_TESTNET_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Conflux
  url: $CONFLUX_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "0x"
  assignees:
    - frontendgatekeeper
- name: RPC server - Harmony
  url: $HARMONY_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "0x"
  assignees:
    - frontendgatekeeper
- name: RPC server - Harmony Test
  url: $HARMONY_TEST_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "0x"
  assignees:
    - frontendgatekeeper
- name: RPC server - Astar
  url: $ASTAR_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":42}'
  __dangerous__body_degraded_if_text_missing: "true"
  assignees:
    - frontendgatekeeper
- name: RPC server - Figment Solana
  url: $FIGMENT_SOLANA_RPC_URL
  method: POST
  headers:
    - "Content-Type: application/json"
  body: '{"jsonrpc":"2.0","method":"getHealth","id":42}'
  __dangerous__body_degraded_if_text_missing: "ok"
# API server used by Mask products
- name: API - Rabby Token
  url: $RABBY_TOKEN_API_URL
  method: GET
  assignees:
    - frontendgatekeeper
# API server used by Mask products
- name: API - Rabby NFT
  url: $RABBY_NFT_API_URL
  method: GET
  assignees:
    - frontendgatekeeper

# web-providers
- name: NFT - Alchemy EVM
  url: $AlchemyEVM_URL
  method: GET
  assignees:
    - frontendgatekeeper

- name: NFT - Alchemy Flow
  url: $AlchemyFlow_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: GasPrice - Astar
  url: $AstarGasnow_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: Asset - Cloudflare
  url: $CloudflareCDN_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: NFT - Chainbase
  url: $Chainbase_URL
  method: GET
  headers:
    - "Content-Type: application/json"
    - "X-API-KEY: YOUR_API_KEY"
  assignees:
    - frontendgatekeeper
- name: Trending - CoinMarketCap Widge
  url: $CmcWidget_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: Trending - CoinMarketCap
  url: $CmcHistorical_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: Trending - CoinGecko
  url: $Coingecko_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: GasPrice - Debank
  url: Debank_Gas_Price_Dict_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: NFT - Debank
  url: $Debian_All_Token_List_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: NFT - Gem
  url: $Gem_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: Security - Gopluslabs
  url: $Gopluslabs_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: NFT - LooksRare
  url: $Looksrare_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: NFT - MagicEden
  url: $MagicEden_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: GasPrice - Metaswap
  url: $Metaswap_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: SNS - Minds
  url: $Minds_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: NFT - NFscan EVM
  url: $NFscan_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: NFT - NFTscan Solana
  url: $NFTscan_Solana_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: Trending - NFTScan
  url: $NFTScan_Trending_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: NFT - Opensea
  url: $Opensea_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: NFT - Rabby
  url: $Rabby_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: NFT - Rarible
  url: $Rarible_URL
  method: GET
  headers:
    - "Content-Type: application/json"
    - "Origin: https://twitter.com"
  assignees:
    - frontendgatekeeper
- name: Pricing - Token View
  url: $Token_view_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper
- name: NFT - X2Y2
  url: $X2Y2_URL
  method: GET
  headers:
    - "Content-Type: application/json"
    - "x-sig: 8a8920fbe2f5dfe8b0ca60b1c2756f7980363e6a82bdcd143cf33ce49940411e"
    - "x-nonce: 1666960301"
    - "x-api-key: 8923f924-1f00-4a6a-b484-088e6ffed7f3"
    - "x-kvv: 2"
  assignees:
    - frontendgatekeeper
- name: NFT - Zora
  url: $Zora_URL
  method: GET
  headers:
    - "Content-Type: application/json"
  assignees:
    - frontendgatekeeper


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mask.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Mask.io Service Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
